# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: outliers.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'outliers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eoutliers.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"r\n\x06Metric\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\nmetrictype\x18\x02 \x01(\x0e\x32\x0e.pb.MetricType\x12\x0b\n\x03pid\x18\x03 \x01(\x05\x12\r\n\x05value\x18\x04 \x01(\x01\".\n\x0fOutliersRequest\x12\x1b\n\x07metrics\x18\x01 \x03(\x0b\x32\n.pb.Metric\"G\n\nPrediction\x12\x0b\n\x03pid\x18\x01 \x01(\x05\x12\x1c\n\x04type\x18\x02 \x01(\x0e\x32\x0e.pb.MetricType\x12\x0e\n\x06result\x18\x03 \x01(\x05\"6\n\x10OutliersResponse\x12\"\n\nprediction\x18\x01 \x03(\x0b\x32\x0e.pb.Prediction*+\n\nMetricType\x12\x07\n\x03\x43PU\x10\x00\x12\n\n\x06MEMORY\x10\x01\x12\x08\n\x04\x44ISK\x10\x02\x32\x41\n\x08Outliers\x12\x35\n\x06\x44\x65tect\x12\x13.pb.OutliersRequest\x1a\x14.pb.OutliersResponse\"\x00\x42\tZ\x07\x65ris/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'outliers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007eris/pb'
  _globals['_METRICTYPE']._serialized_start=348
  _globals['_METRICTYPE']._serialized_end=391
  _globals['_METRIC']._serialized_start=55
  _globals['_METRIC']._serialized_end=169
  _globals['_OUTLIERSREQUEST']._serialized_start=171
  _globals['_OUTLIERSREQUEST']._serialized_end=217
  _globals['_PREDICTION']._serialized_start=219
  _globals['_PREDICTION']._serialized_end=290
  _globals['_OUTLIERSRESPONSE']._serialized_start=292
  _globals['_OUTLIERSRESPONSE']._serialized_end=346
  _globals['_OUTLIERS']._serialized_start=393
  _globals['_OUTLIERS']._serialized_end=458
# @@protoc_insertion_point(module_scope)
