// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: outliers.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType int32

const (
	MetricType_CPU    MetricType = 0
	MetricType_MEMORY MetricType = 1
	MetricType_DISK   MetricType = 2
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "CPU",
		1: "MEMORY",
		2: "DISK",
	}
	MetricType_value = map[string]int32{
		"CPU":    0,
		"MEMORY": 1,
		"DISK":   2,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_outliers_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_outliers_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_outliers_proto_rawDescGZIP(), []int{0}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Metrictype    MetricType             `protobuf:"varint,2,opt,name=metrictype,proto3,enum=pb.MetricType" json:"metrictype,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_outliers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_outliers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_outliers_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Metric) GetMetrictype() MetricType {
	if x != nil {
		return x.Metrictype
	}
	return MetricType_CPU
}

func (x *Metric) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type OutliersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutliersRequest) Reset() {
	*x = OutliersRequest{}
	mi := &file_outliers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutliersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutliersRequest) ProtoMessage() {}

func (x *OutliersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outliers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutliersRequest.ProtoReflect.Descriptor instead.
func (*OutliersRequest) Descriptor() ([]byte, []int) {
	return file_outliers_proto_rawDescGZIP(), []int{1}
}

func (x *OutliersRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Prediction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Type          MetricType             `protobuf:"varint,2,opt,name=type,proto3,enum=pb.MetricType" json:"type,omitempty"`
	Result        int32                  `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"` // -1 for anomaly, 1 for normal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prediction) Reset() {
	*x = Prediction{}
	mi := &file_outliers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prediction) ProtoMessage() {}

func (x *Prediction) ProtoReflect() protoreflect.Message {
	mi := &file_outliers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prediction.ProtoReflect.Descriptor instead.
func (*Prediction) Descriptor() ([]byte, []int) {
	return file_outliers_proto_rawDescGZIP(), []int{2}
}

func (x *Prediction) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Prediction) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_CPU
}

func (x *Prediction) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type OutliersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    []*Prediction          `protobuf:"bytes,1,rep,name=prediction,proto3" json:"prediction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutliersResponse) Reset() {
	*x = OutliersResponse{}
	mi := &file_outliers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutliersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutliersResponse) ProtoMessage() {}

func (x *OutliersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outliers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutliersResponse.ProtoReflect.Descriptor instead.
func (*OutliersResponse) Descriptor() ([]byte, []int) {
	return file_outliers_proto_rawDescGZIP(), []int{3}
}

func (x *OutliersResponse) GetPrediction() []*Prediction {
	if x != nil {
		return x.Prediction
	}
	return nil
}

var File_outliers_proto protoreflect.FileDescriptor

const file_outliers_proto_rawDesc = "" +
	"\n" +
	"\x0eoutliers.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x01\n" +
	"\x06Metric\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12.\n" +
	"\n" +
	"metrictype\x18\x02 \x01(\x0e2\x0e.pb.MetricTypeR\n" +
	"metrictype\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"7\n" +
	"\x0fOutliersRequest\x12$\n" +
	"\ametrics\x18\x01 \x03(\v2\n" +
	".pb.MetricR\ametrics\"Z\n" +
	"\n" +
	"Prediction\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\"\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0e.pb.MetricTypeR\x04type\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x05R\x06result\"B\n" +
	"\x10OutliersResponse\x12.\n" +
	"\n" +
	"prediction\x18\x01 \x03(\v2\x0e.pb.PredictionR\n" +
	"prediction*+\n" +
	"\n" +
	"MetricType\x12\a\n" +
	"\x03CPU\x10\x00\x12\n" +
	"\n" +
	"\x06MEMORY\x10\x01\x12\b\n" +
	"\x04DISK\x10\x022A\n" +
	"\bOutliers\x125\n" +
	"\x06Detect\x12\x13.pb.OutliersRequest\x1a\x14.pb.OutliersResponse\"\x00B\tZ\aeris/pbb\x06proto3"

var (
	file_outliers_proto_rawDescOnce sync.Once
	file_outliers_proto_rawDescData []byte
)

func file_outliers_proto_rawDescGZIP() []byte {
	file_outliers_proto_rawDescOnce.Do(func() {
		file_outliers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outliers_proto_rawDesc), len(file_outliers_proto_rawDesc)))
	})
	return file_outliers_proto_rawDescData
}

var file_outliers_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_outliers_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_outliers_proto_goTypes = []any{
	(MetricType)(0),             // 0: pb.MetricType
	(*Metric)(nil),              // 1: pb.Metric
	(*OutliersRequest)(nil),     // 2: pb.OutliersRequest
	(*Prediction)(nil),          // 3: pb.Prediction
	(*OutliersResponse)(nil),    // 4: pb.OutliersResponse
	(*timestamp.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_outliers_proto_depIdxs = []int32{
	5, // 0: pb.Metric.time:type_name -> google.protobuf.Timestamp
	0, // 1: pb.Metric.metrictype:type_name -> pb.MetricType
	1, // 2: pb.OutliersRequest.metrics:type_name -> pb.Metric
	0, // 3: pb.Prediction.type:type_name -> pb.MetricType
	3, // 4: pb.OutliersResponse.prediction:type_name -> pb.Prediction
	2, // 5: pb.Outliers.Detect:input_type -> pb.OutliersRequest
	4, // 6: pb.Outliers.Detect:output_type -> pb.OutliersResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_outliers_proto_init() }
func file_outliers_proto_init() {
	if File_outliers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outliers_proto_rawDesc), len(file_outliers_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outliers_proto_goTypes,
		DependencyIndexes: file_outliers_proto_depIdxs,
		EnumInfos:         file_outliers_proto_enumTypes,
		MessageInfos:      file_outliers_proto_msgTypes,
	}.Build()
	File_outliers_proto = out.File
	file_outliers_proto_goTypes = nil
	file_outliers_proto_depIdxs = nil
}
